flags: {}
packages:
   - hajong-server/
   - hajong-site/
extra-deps: 
   - utility-ht-0.0.10
   - yesod-auth-account-1.4.1
packages:
   - '../reusable-identifiers'
   - './hajong-server'
   - './hajong-site'
resolver: nightly-2015-06-29
