stanzas:

  # webapp: production
  - type: webapp
    exec: ../dist/bin/hajong-site
    args: [ "config/production-settings.yml" ]
    hosts:
      - funjong.org
    requires-secure: false

  # static files: production
  - type: static-files
    hosts:
      - static.funjong.org
    root: ../static

plugins:
  postgres: true
