static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000" # NB: The port `yesod devel` uses is distinct from this value. Set the `yesod devel` port from the command line.
approot:        "_env:APPROOT:"
ip-from-header: "_env:IP_FROM_HEADER:false"

#analytics: code

copyright: "2016 Samuli Thomasson"

support-to:
   - "someone@example.org"

# hajong server settings
# NOTE: these are read also by hajong which doesn't understand _env's
hajong:
   websocket-addr: "0.0.0.0"
   websocket-port: 8001
   websocket-external-host: "localhost" # site only
   ctrl-secret-ws: "secret"
   db-socket-file: "gameserver.socket"
   logs-directory: "game-logs"

# Database
postgres_database:
   user:     "_env:PGUSER:hajong-site"
   password: "_env:PGPASS:hajong-site"
   host:     "_env:PGHOST:localhost"
   port:     "_env:PGPORT:5432"
   database: "_env:PGDATABASE:hajong-site"
   poolsize: "_env:PGPOOLSIZE:10"

# FB api credentials
facebook_credentials:
   name:   "_env:FB_NAME:appname"
   id:     "_env:FB_ID:appid"
   secret: "_env:FB_SECRET:appsecret"

aws:
   from:       "_env:SES_FROM:app@app.com"
   access-key: "_env:SES_ACCESS_KEY:app@app.com"
   secret-key: "_env:SES_SECRET_KEY:app@app.com"
   region:     "_env:SES_REGION:eu-west-1"
   to: []   # List of addresses where to send a copy of every email produced by the app.

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false
